language: c
install: make

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - |
    if [[ ${TRAVIS_JOB_NUMBER##*.} = "2" ]]; then
      echo enabling coverage for this build
      mv local-coverage.mk local.mk
    fi
  - make test
  - |
    cd client
    ./nup-client
    cd ..

after_success:
  - |
    if [[ ${TRAVIS_JOB_NUMBER##*.} = "2" ]]; then
      curl -so codecov.sh https://codecov.io/bash
      chmod +x codecov.sh
      echo uploading coverage information
      ls client
      ./codecov.sh -Xgcov -s client -s .
    else
      echo coverage not uploaded for this build type
    fi
