language: c
install: make

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - |
    if [[ ${TRAVIS_JOB_NUMBER##*.} = "2" ]]; then
      echo enabling coverage for this build
      mv local-coverage.mk local.mk
    fi
  - make
  - make test

after_success:
  - |
    if [[ ${TRAVIS_JOB_NUMBER##*.} = "2" ]]; then
      bash <(curl -s https://codecov.io/bash)
    else
      echo coverage not uploaded for this build type
    fi
