language: c
install: make

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libsdl2-dev

script:
  - |
    if [[ ${TRAVIS_JOB_NUMBER##*.} = "2" ]]; then
      echo enabling coverage for this build
      mv local-coverage.mk local.mk
    fi
  - make test

after_success:
  - |
    if [[ ${TRAVIS_JOB_NUMBER##*.} = "2" ]]; then
      curl -so codecov.sh https://codecov.io/bash
      chmod +x codecov.sh
      echo uploading coverage information
      ./codecov.sh -Xgcov
    else
      echo coverage not uploaded for this build type
    fi
